### ISSUE TITLE
 Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by ybyd2005** [Morningstar/kafka-offset-monitor#11]
I using this parameters:

`java -cp KafkaOffsetMonitor-assembly-0.4.0.jar \ com.quantifind.kafka.offsetapp.OffsetGetterWeb \ --zk 172.19.6.222 \ --port 2288 \ --refresh 10.seconds \ --retain 2.days \ --dbName offsetapp_kafka`

But when I started, there was a problem：

`serving resources from: jar:file:/root/KafkaOffsetMonitor-assembly-0.4.0.jar!/offsetapp Exception in thread "main" java.lang.UnsupportedClassVersionError: com/twitter/util/Time : Unsupported major.minor version 52.0 at java.lang.ClassLoader.defineClass1(Native Method) at java.lang.ClassLoader.defineClass(ClassLoader.java:791) at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) at java.net.URLClassLoader.access$100(URLClassLoader.java:71) at java.net.URLClassLoader$1.run(URLClassLoader.java:361) at java.net.URLClassLoader$1.run(URLClassLoader.java:355) at java.security.AccessController.doPrivileged(Native Method) at java.net.URLClassLoader.findClass(URLClassLoader.java:354) at java.lang.ClassLoader.loadClass(ClassLoader.java:423) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) at java.lang.ClassLoader.loadClass(ClassLoader.java:356) at com.quantifind.kafka.offsetapp.OffsetGetterWeb$TimeSerializer.<init>(OffsetGetterWeb.scala:126) at com.quantifind.kafka.offsetapp.OffsetGetterWeb$$anon$1.<init>(OffsetGetterWeb.scala:138) at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.setup(OffsetGetterWeb.scala:137) at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.setup(OffsetGetterWeb.scala:46) at com.quantifind.utils.UnfilteredWebApp$class.main(UnfilteredWebApp.scala:29) at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.main(OffsetGetterWeb.scala:46) at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.main(OffsetGetterWeb.scala:46) at com.quantifind.sumac.ArgMain$class.mainHelper(ArgApp.scala:45) at com.quantifind.sumac.ArgMain$class.main(ArgApp.scala:34) at com.quantifind.kafka.offsetapp.OffsetGetterWeb$.main(OffsetGetterWeb.scala:46) at com.quantifind.kafka.offsetapp.OffsetGetterWeb.main(OffsetGetterWeb.scala)`

**Comment by sheeeee94** [comment]
I also have the same problem. I am waiting for a reply.

**Comment by rcasey212** [comment]
If you are running the pre-built release, please run it with JRE 8. Thanks!
