### ISSUE TITLE
Is not "0.11" version supported?

### ISSUE THREAD

**Issue by taetaetae** [Morningstar/kafka-offset-monitor#12]
In "0.11" version, it does not seem to be activated as shown below.
![image](https://user-images.githubusercontent.com/10969354/32314325-ad2e39b6-bfea-11e7-85e5-a5be015e215b.png)

Note that "kafka" is working normally and "producer" and "consumer" are working well.

help me...

**Comment by rcasey212** [comment]
Hi @taetaetae , It appears you do not have an active consumer for the topic to which you inquired.

Do you have any errors in the log which you can share?

**Comment by taetaetae** [comment]
I didn't see any particular errors.
What kind of " Active Consumer " is selected?  " Consumer " already exists, and there is no " Active Consumer ".

**Comment by taetaetae** [comment]
@rcasey212 
How do I create "Active Consumers"?
There seems to be enough messages.
![image](https://user-images.githubusercontent.com/10969354/32990125-25d3c3ac-cd67-11e7-8804-328a732d2f35.png)

**Comment by rcasey212** [comment]
Hi @taetaetae,

An active consumer is a Kafka consumer which is currently running and connected to a Kafka broker.

**Comment by taetaetae** [comment]
@rcasey212 
> connected to a Kafka broker.

I do not understand this part well.

producer, consumer, and linking to the same topic.
Consumer is currently in operation, but the part that does not come out as active consumer is not understood well.
Does it work well in version 11?

**Comment by rcasey212** [comment]
Hi @taetaetae : kafka-offset-monitor is currently untested in 0.11.
