### ISSUE TITLE
start failure and the page is empty

### ISSUE THREAD

**Issue by zhangpfly** [Morningstar/kafka-offset-monitor#16]
start failure
![image](https://user-images.githubusercontent.com/17722518/35139323-8dbd33e0-fd2d-11e7-808f-f5803cd480ea.png)
empty pages
![image](https://user-images.githubusercontent.com/17722518/35139358-b111b7c6-fd2d-11e7-9ca9-b61add360c92.png)

**Comment by rcasey212** [comment]
The file does not exist.

You passed it on the command line here:
![image](https://user-images.githubusercontent.com/7251156/35172181-33648bd8-fd2c-11e7-8c87-e35ff4b6962e.png)

If you are using SASL_PLAINTEXT for security, you need a jaas.conf file to configure the security mechanism.  There is much to read regarding Kafka security - this is a good starting point: https://www.confluent.io/blog/apache-kafka-security-authorization-authentication-encryption/

Hope that helps.
