### ISSUE TITLE
Not showing consumer offsets in some environments

### ISSUE THREAD

**Issue by robamaton** [Morningstar/kafka-offset-monitor#19]
Thanks for the great app! I'm using v0.4.6 with Kafka 0.11 and it works great in a local docker-compose environment, but I'm having trouble when deploying to DC/OS (Mesos).

In one deployment environment, I can see all  topics, consumers, partitions, and log-end offsets, but there are no consumer offsets. I can see "Updating committed offset" messages when I send new messages through Kafka. However, the async call from the Offset History page always returns `offsets: []`.

In one of the other environments, it's a it worse since you can see the topics and consumers, but no offset information at all or visibility into the partitions. The two environments use different flavors of Zookeeper but are otherwise similar.

Any ideas?

**Comment by rcasey212** [comment]
Hi @robamaton,

I can only guess without getting more information from you.

In the first instance, perhaps you have chosen the incorrect offsetStorage option for your environment?

In the second instance, I'm guessing there is a connectivity issue between the monitor and your Kafka broker, or ZooKeeper node(s).

Can you provide your config for kafka-offset-monitor and some logs?


Thanks,
Bob
