### ISSUE TITLE
angular.js missing

### ISSUE THREAD

**Issue by clennpillo** [Morningstar/kafka-offset-monitor#25]
at around Mar. 26th 2018, angularJS referenced by index.html is not available 'cause ajax.googleapis.com/ajax/libs/angularjs/1.2.9/angular.js is no longer at where it previously was,
need to fix the issue

**Comment by clennpillo** [comment]
workaround: for version 0.4.6
1. download corresponding angular js files from https://code.angularjs.org, in my case version 1.2.9
2. put three files in src/main/resources/offsetapp/scripts folder and replace code in src/main/resources/offsetapp/index.html
before 
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.9/angular.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.9/angular-route.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.9/angular-resource.js"></script>
after
<script src="./scripts/angular.js"></script>
<script src="./scripts/angular-route.js"></script>
<script src="./scripts/angular-resource.js"></script>
3. sbt clean assembly to generate a new jar file

**Comment by rcasey212** [comment]
Nothing has changed.  Angular is still available at the same URL.  Maybe you have a firewall?
