### ISSUE TITLE
Could not find or load main class com.quantifind.kafka.offsetapp.OffsetGetterWeb

### ISSUE THREAD

**Issue by lancelakey** [Morningstar/kafka-offset-monitor#30]
I'm using `KafkaOffsetMonitor-assembly-0.4.6-SNAPSHOT.jar` and JDK 7

```
dpkg -l | grep -i jdk
ii  openjdk-7-jdk:amd64                   7u111-2.6.7-0ubuntu0.14.04.3     amd64        OpenJDK Development Kit (JDK)
ii  openjdk-7-jre:amd64                   7u111-2.6.7-0ubuntu0.14.04.3     amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-7-jre-headless:amd64          7u111-2.6.7-0ubuntu0.14.04.3     amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
```

What might cause this error?

`java -cp KafkaOffsetMonitor-assembly-0.4.6.jar com.quantifind.kafka.offsetapp.OffsetGetterWeb` ...

`Error: Could not find or load main class com.quantifind.kafka.offsetapp.OffsetGetterWeb`

**Comment by rcasey212** [comment]
Hi @lancelakey,

JRE v8 is required to run this project.
