### ISSUE TITLE
Doesn't Launch

### ISSUE THREAD

**Issue by DivsDibs** [Morningstar/kafka-offset-monitor#33]
Launch fails with the message
`Could not find or load main class com.quantifind.kafka.offsetapp.OffsetGetterWeb`

I ran the same command present in the README in the same dir where the Jar is downloaded. 

```
java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

[root@npe-tfb-kfk-w2a-a6 opt]# alternatives --config java

There are 3 programs which provide 'java'.

  Selection    Command
-----------------------------------------------
   1           /opt/jdk1.8.0_181/bin/java
   2           /opt/jdk1.8.0_181/jre/bin/java
*+ 3           /opt/jre1.8.0_181/bin/java
```

**Comment by yluom** [comment]
Hello, your launch command is probably referencing the wrong jar.
For example, the readme launch command references  
`-cp KafkaOffsetMonitor-assembly-0.4.6.jar`
but the lastest jar is called 
`-cp KafkaOffsetMonitor-assembly-0.4.6-SNAPSHOT.jar`
Does that helps ? ;)

**Comment by williamla** [comment]
> Hello, your launch command is probably referencing the wrong jar.

Ran into this error and it wasn't until I found this open issue that I noticed it too. Thanks!

**Comment by rcasey212** [comment]
Sorry you all were having trouble with the start-up command.  I've updated the README to help with this.  Thanks.
